hs = struct;
% add components, save handles in a struct

    %hs.g = uigauge;
    %hs.fig = gcf;

hs.fig = figure('Visible','on',...
    'Resize','on',...
    'Tag','fig');
hs.btn = uicontrol(hs.fig,'Position',[10 340 70 30],...
    'String','Start simulation',...
    'Tag','button',...
    'Callback','GUI_main_calc2D_concept2');
hs.btn = uicontrol(hs.fig,'Position',[10 240 70 30],...
    'String','Pause',...
    'Tag','button',...
    'Callback','GUI_pause');
hs.btn = uicontrol(hs.fig,'Position',[10 140 70 30],...
    'String','Stop',...
    'Tag','button',...
    'Callback','GUI_stop');

%!we create all gauges in a separate

hs.gfig = uifigure;
hs.gthrottle = uigauge(hs.gfig, 'circular', 'Position', [50 50 150 150], 'limits', [0 100], 'ScaleDirection', 'clockwise');
hs.gthrust = uigauge(hs.gfig, 'circular', 'Position', [300 50 150 150], 'limits', [0 200], 'ScaleDirection', 'clockwise');


hs.ax = axes('Parent',hs.fig,...
    'Position',[0.20 0.13 0.71 0.75],...
    'Tag','ax');


pauseflag = false;
simulateflag = false;
