function GUI_start()

global pauseflag simulateflag hs record_flag vid

record_flag = false; %can be set to TRUE in GUI_main_calc2D_toy.m

hs = struct;
% add components, save handles in a struct

    %hs.g = uigauge;
    %hs.fig = gcf;

hs.fig = figure('Visible','on',...
    'Resize','on',...
    'Tag','fig', 'KeyPressFcn', @keyPress);
hs.btn1 = uicontrol(hs.fig,'Position',[10 340 70 30],...
    'String','Start simulation',...
    'Tag','button',...
    'Callback','GUI_main_calc2D_toy');
hs.btn2 = uicontrol(hs.fig,'Position',[10 240 70 30],...
    'String','Pause',...
    'Tag','button',...
    'Callback','GUI_pause');
hs.btn3 = uicontrol(hs.fig,'Position',[10 140 70 30],...
    'String','Stop',...
    'Tag','button',...
    'Callback','GUI_stop');


%!we create all gauges in a separate figure
% hs.gfig = uifigure;
% hs.gthrottle = uigauge(hs.gfig, 'circular', 'Position', [50 50 150 150], 'limits', [0 100], 'ScaleDirection', 'clockwise');
% hs.gthrust = uigauge(hs.gfig, 'circular', 'Position', [300 50 150 150], 'limits', [0 200], 'ScaleDirection', 'clockwise');


hs.ax = axes('Parent',hs.fig,...
    'Position',[0.20 0.13 0.71 0.75],...
    'Tag','ax');


pauseflag = false;
simulateflag = false;
